### ISSUE TITLE
Copy Master into Sublayer: AttributeError: can’t set attribute

### ISSUE THREAD

**Issue by chrisjansky** [harbortype/glyphs-scripts#1]
Using the latest version of the script with latest vanilla in Glyphs 3081 produces the following error:

<img width="992" alt="Screenshot 2021-05-03 at 14 03 16" src="https://user-images.githubusercontent.com/5342612/116873783-883fb080-ac18-11eb-9fa2-24dfb4b72db7.png">

**Comment by harbortype** [comment]
@chrisjansky Thank you for letting me know about this. I just published a fix for this script.

**Comment by chrisjansky** [comment]
@harbortype Perfect, thanks for fixing it so quickly!

**Comment by harbortype** [comment]
@chrisjansky No problem! If you find anything else to be broken, just let me know.
